### ISSUE TITLE
npm start:hmr drops error

### ISSUE THREAD

**Issue by 4i-helpynet** [Syntaf/angular4-barefuckinbones#1]
After a clean node.js, npm, npm install, the npm start:hmr // hot module replacement command not work. I try the npm start --hmr too, but it's look like normal npm start...

**Comment by Syntaf** [comment]
Ah dang. Sorry! I'm currently in France for the next two weeks. When I return I will plan on fixing this issue as well as upgrading the repo to use the AoT compiler

**Comment by 4i-helpynet** [comment]
Please let me inform when you can fix it - we still want to use this in our project.
Thank you

**Comment by Syntaf** [comment]
@4i-helpynet apologies, I somehow forgot about this issue. I'm working on it atm to see what the issue is.

**Comment by Syntaf** [comment]
What kind of error are you getting? I just updated some packaged and ran `npm run start:hmr` with no errors.

**Comment by 4i-helpynet** [comment]
I update the repo and it's worked, thanks. \o/
